# -*- coding: utf-8 -*-
"""compliance_scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEgqYKr0NkAftCEXjIaOOYVgvwtqqYaM
"""

"""
=============================================================================
DUAL-JURISDICTION CLOUD STORAGE COMPLIANCE SCANNER
=============================================================================
Research tool for: "Cloud Data Localisation Compliance under Russia's
Federal Law 242-FZ and India's DPDPA Act 2023"

Checks cloud storage bucket configuration against clause-level requirements
extracted from the DPDPA 2023 / 152-FZ compliance matrix.

MODES:
  Mode A — Real AWS S3 bucket (requires boto3 + AWS credentials)
  Mode B — Simulated config dictionary (no cloud access needed)

USAGE:
  python compliance_scanner.py --mode b                    # simulated
  python compliance_scanner.py --mode a --bucket my-bucket # real AWS
  python compliance_scanner.py --mode a --bucket my-bucket --region eu-west-1
  python compliance_scanner.py --mode b --scenario fail    # all-fail demo
  python compliance_scanner.py --mode b --scenario pass    # all-pass demo
  python compliance_scanner.py --mode b --scenario mixed   # realistic mix

OUTPUT:
  Console report + optional JSON export (--json output.json)
=============================================================================
"""

import argparse
import json
import sys
from datetime import datetime, timezone


# ═══════════════════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════════════════

VERSION = "1.0.0"

# Russian cloud regions — data must be primarily stored here under 242-FZ
RUSSIAN_REGIONS = {
    "ru-central1",        # Yandex Cloud Moscow
    "ru-northwest1",      # Yandex Cloud St. Petersburg
    "ru-central1-a",
    "ru-central1-b",
    "ru-central1-c",
    "russia",
    "russia-1",
    "sbercloud-ru",
    "mcs-ru-1",           # Mail.ru Cloud Solutions
}

# DPDPA S.16 blacklist — currently empty (no country notified as of 2026)
# In a production system this would be fetched from a live registry feed
DPDPA_BLACKLISTED_REGIONS = set()

# Regions that are clearly non-Russian (for 242-FZ failure detection)
NON_RUSSIAN_REGION_PREFIXES = [
    "us-", "eu-", "ap-", "ca-", "sa-", "af-", "me-",
    "eastus", "westus", "northeurope", "westeurope",
    "southeastasia", "eastasia", "australiaeast",
]

# Encryption algorithms considered acceptable under DPDPA S.8(5)
DPDPA_ACCEPTABLE_ALGORITHMS = {
    "AES256", "AES-256", "aws:kms", "aws:kms:dsse",
    "RSA", "AES", "TLS", "HTTPS"
}

# Encryption algorithms that satisfy 152-FZ Art.19(3b) (FSB-certified GOST)
FZ_ACCEPTABLE_ALGORITHMS = {
    "GOST", "GOST R 34.12-2015", "GOST-256", "GOST-512",
    "CRYPTOPRO", "VIPNET", "GOST3412-2015"
}


# ═══════════════════════════════════════════════════════════════════════════
# RESULT CLASSES
# ═══════════════════════════════════════════════════════════════════════════

class CheckResult:
    PASS    = "PASS"
    FAIL    = "FAIL"
    WARN    = "WARN"
    SKIP    = "SKIP"

    def __init__(self, clause_id, check_name, status, detail, recommendation=None):
        self.clause_id      = clause_id
        self.check_name     = check_name
        self.status         = status
        self.detail         = detail
        self.recommendation = recommendation

    def to_dict(self):
        return {
            "clause_id":      self.clause_id,
            "check_name":     self.check_name,
            "status":         self.status,
            "detail":         self.detail,
            "recommendation": self.recommendation,
        }


class ConflictResult:
    ACTIVE   = "ACTIVE"
    INACTIVE = "INACTIVE"

    def __init__(self, conflict_id, laws, status, detail, recommendation):
        self.conflict_id     = conflict_id
        self.laws            = laws
        self.status          = status
        self.detail          = detail
        self.recommendation  = recommendation

    def to_dict(self):
        return {
            "conflict_id":    self.conflict_id,
            "laws":           self.laws,
            "status":         self.status,
            "detail":         self.detail,
            "recommendation": self.recommendation,
        }


# ═══════════════════════════════════════════════════════════════════════════
# SIMULATED CONFIGURATIONS (Mode B)
# ═══════════════════════════════════════════════════════════════════════════

SIMULATED_CONFIGS = {
    # Realistic mixed scenario — some pass, some fail, conflicts triggered
    "mixed": {
        "bucket_name":         "test-bucket-research-mixed",
        "region":              "us-east-1",
        "encryption_enabled":  True,
        "encryption_algorithm":"AES256",
        "public_access_blocked": True,
        "versioning_enabled":  False,
        "logging_enabled":     False,
        "retention_policy_set": False,
        "https_only_enforced": True,
        "data_subject_origin": "both",    # "russian", "indian", or "both"
        "is_pdis":             True,      # Is this a Personal Data Info System under 152-FZ?
    },
    # All-pass scenario (hypothetical dual-compliant config)
    "pass": {
        "bucket_name":          "test-bucket-research-pass",
        "region":               "ru-central1",
        "encryption_enabled":   True,
        "encryption_algorithm": "GOST R 34.12-2015",
        "public_access_blocked": True,
        "versioning_enabled":   True,
        "logging_enabled":      True,
        "retention_policy_set": True,
        "https_only_enforced":  True,
        "data_subject_origin":  "both",
        "is_pdis":              True,
    },
    # All-fail scenario — demonstrates every failure mode
    "fail": {
        "bucket_name":          "test-bucket-research-fail",
        "region":               "eu-west-1",
        "encryption_enabled":   False,
        "encryption_algorithm": None,
        "public_access_blocked": False,
        "versioning_enabled":   False,
        "logging_enabled":      False,
        "retention_policy_set": False,
        "https_only_enforced":  False,
        "data_subject_origin":  "both",
        "is_pdis":              True,
    },
    # Indian-only scenario — only DPDPA applies
    "india_only": {
        "bucket_name":          "test-bucket-india-only",
        "region":               "ap-south-1",
        "encryption_enabled":   True,
        "encryption_algorithm": "AES256",
        "public_access_blocked": True,
        "versioning_enabled":   True,
        "logging_enabled":      True,
        "retention_policy_set": True,
        "https_only_enforced":  True,
        "data_subject_origin":  "indian",
        "is_pdis":              False,
    },
}


# ═══════════════════════════════════════════════════════════════════════════
# MODE A: AWS S3 REAL CONFIG FETCHER
# ═══════════════════════════════════════════════════════════════════════════

def fetch_aws_config(bucket_name, region=None):
    """
    Fetch real S3 bucket configuration using boto3.
    Returns a config dict in the same format as simulated configs.
    """
    try:
        import boto3
        from botocore.exceptions import ClientError, NoCredentialsError
    except ImportError:
        print("\n  ERROR: boto3 is not installed.")
        print("  Run: pip install boto3")
        print("  Then configure AWS credentials:")
        print("    aws configure")
        print("  Or set environment variables:")
        print("    export AWS_ACCESS_KEY_ID=your_key")
        print("    export AWS_SECRET_ACCESS_KEY=your_secret")
        print("    export AWS_DEFAULT_REGION=us-east-1\n")
        sys.exit(1)

    try:
        client = boto3.client("s3", region_name=region)
        print(f"\n  Connecting to AWS S3...")
        print(f"  Fetching configuration for bucket: {bucket_name}")

        config = {
            "bucket_name":          bucket_name,
            "region":               "unknown",
            "encryption_enabled":   False,
            "encryption_algorithm": None,
            "public_access_blocked": False,
            "versioning_enabled":   False,
            "logging_enabled":      False,
            "retention_policy_set": False,
            "https_only_enforced":  False,
            "data_subject_origin":  "both",  # Conservative: assume both
            "is_pdis":              True,     # Conservative: assume PDIS
        }

        # ── Region ─────────────────────────────────────────────────────
        try:
            loc = client.get_bucket_location(Bucket=bucket_name)
            raw_region = loc.get("LocationConstraint") or "us-east-1"
            config["region"] = raw_region
            print(f"  [1/7] Region: {raw_region}")
        except ClientError as e:
            print(f"  [1/7] Region: FETCH ERROR — {e.response['Error']['Code']}")

        # ── Encryption ─────────────────────────────────────────────────
        try:
            enc = client.get_bucket_encryption(Bucket=bucket_name)
            rules = enc["ServerSideEncryptionConfiguration"]["Rules"]
            if rules:
                algo = rules[0]["ApplyServerSideEncryptionByDefault"]["SSEAlgorithm"]
                config["encryption_enabled"]   = True
                config["encryption_algorithm"] = algo
                print(f"  [2/7] Encryption: ENABLED ({algo})")
            else:
                print(f"  [2/7] Encryption: DISABLED (no rules)")
        except ClientError as e:
            code = e.response["Error"]["Code"]
            if code == "ServerSideEncryptionConfigurationNotFoundError":
                print(f"  [2/7] Encryption: DISABLED (not configured)")
            else:
                print(f"  [2/7] Encryption: FETCH ERROR — {code}")

        # ── Public Access Block ────────────────────────────────────────
        try:
            pub = client.get_public_access_block(Bucket=bucket_name)
            cfg = pub["PublicAccessBlockConfiguration"]
            all_blocked = all([
                cfg.get("BlockPublicAcls", False),
                cfg.get("IgnorePublicAcls", False),
                cfg.get("BlockPublicPolicy", False),
                cfg.get("RestrictPublicBuckets", False),
            ])
            config["public_access_blocked"] = all_blocked
            status = "ALL BLOCKED" if all_blocked else "PARTIALLY OPEN"
            print(f"  [3/7] Public access: {status}")
        except ClientError as e:
            code = e.response["Error"]["Code"]
            if code == "NoSuchPublicAccessBlockConfiguration":
                print(f"  [3/7] Public access: NOT CONFIGURED (open by default)")
            else:
                print(f"  [3/7] Public access: FETCH ERROR — {code}")

        # ── Versioning ────────────────────────────────────────────────
        try:
            ver = client.get_bucket_versioning(Bucket=bucket_name)
            enabled = ver.get("Status") == "Enabled"
            config["versioning_enabled"] = enabled
            print(f"  [4/7] Versioning: {'ENABLED' if enabled else 'DISABLED'}")
        except ClientError as e:
            print(f"  [4/7] Versioning: FETCH ERROR — {e.response['Error']['Code']}")

        # ── Logging ───────────────────────────────────────────────────
        try:
            log = client.get_bucket_logging(Bucket=bucket_name)
            enabled = "LoggingEnabled" in log
            config["logging_enabled"] = enabled
            if enabled:
                target = log["LoggingEnabled"].get("TargetBucket", "same bucket")
                print(f"  [5/7] Logging: ENABLED (→ {target})")
            else:
                print(f"  [5/7] Logging: DISABLED")
        except ClientError as e:
            print(f"  [5/7] Logging: FETCH ERROR — {e.response['Error']['Code']}")

        # ── Lifecycle / Retention ─────────────────────────────────────
        try:
            lc = client.get_bucket_lifecycle_configuration(Bucket=bucket_name)
            rules = lc.get("Rules", [])
            has_expiry = any(
                "Expiration" in r or "NoncurrentVersionExpiration" in r
                for r in rules
            )
            config["retention_policy_set"] = has_expiry
            print(f"  [6/7] Lifecycle policy: {'SET' if has_expiry else 'NO EXPIRY RULES'} ({len(rules)} rules)")
        except ClientError as e:
            code = e.response["Error"]["Code"]
            if code in ("NoSuchLifecycleConfiguration", "NoSuchBucketPolicy"):
                print(f"  [6/7] Lifecycle policy: NOT CONFIGURED")
            else:
                print(f"  [6/7] Lifecycle policy: FETCH ERROR — {code}")

        # ── HTTPS-only bucket policy ──────────────────────────────────
        try:
            pol = client.get_bucket_policy(Bucket=bucket_name)
            policy_doc = json.loads(pol["Policy"])
            https_only = False
            for stmt in policy_doc.get("Statement", []):
                cond = stmt.get("Condition", {})
                if "Bool" in cond:
                    val = cond["Bool"].get("aws:SecureTransport")
                    if val in ("false", False) and stmt.get("Effect") == "Deny":
                        https_only = True
                        break
            config["https_only_enforced"] = https_only
            print(f"  [7/7] HTTPS-only: {'ENFORCED' if https_only else 'NOT ENFORCED'}")
        except ClientError as e:
            code = e.response["Error"]["Code"]
            if code == "NoSuchBucketPolicy":
                print(f"  [7/7] HTTPS-only: NO BUCKET POLICY (not enforced)")
            else:
                print(f"  [7/7] HTTPS-only: FETCH ERROR — {code}")

        print()
        return config

    except Exception as e:
        print(f"\n  FATAL: Could not connect to AWS — {e}")
        print("  Check your AWS credentials and bucket name.\n")
        sys.exit(1)


# ═══════════════════════════════════════════════════════════════════════════
# COMPLIANCE CHECKS
# ═══════════════════════════════════════════════════════════════════════════

def run_checks(config):
    """Run all clause-level compliance checks against the config."""
    results = []
    region  = config.get("region", "unknown").lower()
    origin  = config.get("data_subject_origin", "both")
    is_pdis = config.get("is_pdis", True)

    # ── CHECK 1: 242-FZ Art.18(5) — Russian region ───────────────────────
    if origin in ("russian", "both"):
        is_russian = (
            region in RUSSIAN_REGIONS or
            any(region.startswith(p) for p in ["ru-", "russia"])
        )
        if is_russian:
            results.append(CheckResult(
                "242FZ-A18(5)",
                "Storage region (Russia primary)",
                CheckResult.PASS,
                f"Region '{region}' is a Russian-territory storage location.",
            ))
        else:
            results.append(CheckResult(
                "242FZ-A18(5)",
                "Storage region (Russia primary)",
                CheckResult.FAIL,
                f"Region '{region}' is not a Russian territory. Russian citizen data "
                f"must be initially stored in Russia (242-FZ Art.18(5)).",
                "Deploy a separate Russian-region primary bucket (Yandex Cloud "
                "ru-central1 or SberCloud). Route Russian citizen data writes there "
                "before any other processing.",
            ))
    else:
        results.append(CheckResult(
            "242FZ-A18(5)",
            "Storage region (Russia primary)",
            CheckResult.SKIP,
            "Data subject origin is Indian only — 242-FZ localisation does not apply.",
        ))

    # ── CHECK 2: DPDP-S16 — DPDPA blacklist ──────────────────────────────
    region_blacklisted = region in DPDPA_BLACKLISTED_REGIONS
    if region_blacklisted:
        results.append(CheckResult(
            "DPDP-S16",
            "Storage region (DPDPA blacklist)",
            CheckResult.FAIL,
            f"Region '{region}' is in a country notified as restricted under DPDPA S.16.",
            "Migrate data to a non-blacklisted region. Review Central Government "
            "notifications under DPDPA S.16 for the current restricted list.",
        ))
    else:
        results.append(CheckResult(
            "DPDP-S16",
            "Storage region (DPDPA blacklist)",
            CheckResult.PASS,
            f"Region '{region}' is not in any country currently blacklisted under "
            f"DPDPA S.16. No Central Government restriction notification is active.",
        ))

    # ── CHECK 3: DPDP-S8(5) — Encryption at rest ─────────────────────────
    enc_enabled = config.get("encryption_enabled", False)
    enc_algo    = config.get("encryption_algorithm") or ""
    if enc_enabled:
        algo_upper = enc_algo.upper()
        is_dpdpa_ok = any(a.upper() in algo_upper for a in DPDPA_ACCEPTABLE_ALGORITHMS) or len(algo_upper) > 0
        if is_dpdpa_ok:
            results.append(CheckResult(
                "DPDP-S8(5)",
                "Encryption at rest",
                CheckResult.PASS,
                f"Encryption is enabled using '{enc_algo}'. This satisfies DPDPA S.8(5) "
                f"reasonable security safeguards standard.",
            ))
        else:
            results.append(CheckResult(
                "DPDP-S8(5)",
                "Encryption at rest",
                CheckResult.WARN,
                f"Encryption is enabled but algorithm '{enc_algo}' could not be verified "
                f"against known acceptable standards.",
                "Confirm the encryption algorithm meets industry standards (AES-256 minimum).",
            ))
    else:
        results.append(CheckResult(
            "DPDP-S8(5)",
            "Encryption at rest",
            CheckResult.FAIL,
            "Encryption at rest is NOT enabled. This violates DPDPA S.8(5) reasonable "
            "security safeguards obligation. Penalty up to INR 250 crore.",
            "Enable server-side encryption immediately. Use AES-256 at minimum.",
        ))

    # ── CHECK 4: 152FZ-A19(3b) — GOST encryption standard ───────────────
    if is_pdis and origin in ("russian", "both"):
        algo_upper = enc_algo.upper() if enc_algo else ""
        is_gost = any(g.upper() in algo_upper for g in FZ_ACCEPTABLE_ALGORITHMS)
        is_aes  = "AES" in algo_upper or "KMS" in algo_upper

        if is_gost:
            results.append(CheckResult(
                "152FZ-A19(3b)",
                "Encryption standard (GOST)",
                CheckResult.PASS,
                f"FSB-certified GOST algorithm detected ('{enc_algo}'). Satisfies "
                f"152-FZ Art.19(3b) mandatory certified tool requirement for PDIS.",
            ))
        elif is_aes and enc_enabled:
            results.append(CheckResult(
                "152FZ-A19(3b)",
                "Encryption standard (GOST)",
                CheckResult.WARN,
                f"Standard algorithm detected ('{enc_algo}'). AES satisfies DPDPA but "
                f"does NOT satisfy 152-FZ Art.19(3b) for regulated PDIS — FSB-certified "
                f"GOST tools are mandatory.",
                "Implement CONFLICT-03 hybrid by data type: use FSB-certified GOST tools "
                "(CryptoPro CSP or ViPNet) for Russian PDIS data. AES remains for "
                "non-Russian data. Separate HSM and PKI required.",
            ))
        else:
            results.append(CheckResult(
                "152FZ-A19(3b)",
                "Encryption standard (GOST)",
                CheckResult.FAIL,
                "No encryption detected. 152-FZ Art.19(3b) requires FSB-certified GOST "
                "cryptographic tools in all regulated PDIS.",
                "Deploy FSB-certified GOST encryption (CryptoPro or ViPNet) immediately. "
                "This is a verifiable technical violation auditable by FSTEC.",
            ))
    else:
        results.append(CheckResult(
            "152FZ-A19(3b)",
            "Encryption standard (GOST)",
            CheckResult.SKIP,
            "Not a regulated PDIS or no Russian data subjects — 152-FZ Art.19(3b) "
            "GOST certification check not applicable.",
        ))

    # ── CHECK 5: DPDP-S8(5) — Public access blocked ──────────────────────
    public_blocked = config.get("public_access_blocked", False)
    if public_blocked:
        results.append(CheckResult(
            "DPDP-S8(5)",
            "Public access blocked",
            CheckResult.PASS,
            "Public access is fully disabled. Satisfies DPDPA S.8(5) reasonable "
            "security safeguards and 152-FZ Art.7 non-disclosure obligations.",
        ))
    else:
        results.append(CheckResult(
            "DPDP-S8(5)",
            "Public access blocked",
            CheckResult.FAIL,
            "Public access is NOT fully blocked. Personal data in this storage "
            "may be accessible to unauthorised parties.",
            "Enable all four public access block settings: BlockPublicAcls, "
            "IgnorePublicAcls, BlockPublicPolicy, RestrictPublicBuckets.",
        ))

    # ── CHECK 6: 152FZ-A19 / DPDP-S8(5) — Versioning ────────────────────
    versioning = config.get("versioning_enabled", False)
    if versioning:
        results.append(CheckResult(
            "152FZ-A19(8)",
            "Versioning enabled (audit trail)",
            CheckResult.PASS,
            "Object versioning is enabled. Supports immutable audit trail requirement "
            "under 152-FZ Art.19(8) and DPDPA S.6(10) consent log preservation.",
        ))
    else:
        results.append(CheckResult(
            "152FZ-A19(8)",
            "Versioning enabled (audit trail)",
            CheckResult.FAIL,
            "Object versioning is NOT enabled. 152-FZ Art.19(8) requires all actions "
            "involving personal data to be registered and recorded. Without versioning, "
            "records can be silently overwritten or deleted.",
            "Enable bucket versioning. Configure lifecycle rules to transition old "
            "versions to cheaper storage rather than immediate deletion.",
        ))

    # ── CHECK 7: 152FZ-A19 / DPDP-S8(5) — Access logging ────────────────
    logging_enabled = config.get("logging_enabled", False)
    if logging_enabled:
        results.append(CheckResult(
            "DPDP-S8(5) / 152FZ-A19",
            "Access logging enabled",
            CheckResult.PASS,
            "Access logging is configured. Satisfies DPDPA S.8(5) security safeguards "
            "and 152-FZ Art.19(8) requirement to register all actions involving "
            "personal data in PDIS.",
        ))
    else:
        results.append(CheckResult(
            "DPDP-S8(5) / 152FZ-A19",
            "Access logging enabled",
            CheckResult.FAIL,
            "Access logging is NOT configured. Both DPDPA S.8(5) and 152-FZ Art.19(8) "
            "require access logs for personal data storage. Without logging, breach "
            "detection and regulatory evidence production are impossible.",
            "Enable server access logging to a separate dedicated log bucket. "
            "Set log retention to at least 1 year. Enable SIEM integration.",
        ))

    # ── CHECK 8: DPDP-S8(7) / 152FZ-A5(7) — Retention policy ────────────
    retention = config.get("retention_policy_set", False)
    if retention:
        results.append(CheckResult(
            "DPDP-S8(7) / 152FZ-A5(7)",
            "Retention / deletion policy",
            CheckResult.PASS,
            "A lifecycle / retention policy is configured. Supports DPDPA S.8(7) "
            "erasure obligation and 152-FZ Art.5(7) storage limitation principle. "
            "Verify policy enforces deletion when purpose is achieved.",
        ))
    else:
        results.append(CheckResult(
            "DPDP-S8(7) / 152FZ-A5(7)",
            "Retention / deletion policy",
            CheckResult.FAIL,
            "No retention or lifecycle deletion policy found. DPDPA S.8(7) requires "
            "erasure when the processing purpose is no longer served. 152-FZ Art.5(7) "
            "requires destruction once processing purpose is attained.",
            "Create a lifecycle policy with expiry rules mapped to each data type's "
            "retention period. Implement legal hold flags for data subject to sector-law "
            "retention overrides (e.g., banking: 10 years under RBI KYC Directions).",
        ))

    # ── CHECK 9: DPDP-S8(5) / 152FZ-A19 — HTTPS only ────────────────────
    https_only = config.get("https_only_enforced", False)
    if https_only:
        results.append(CheckResult(
            "DPDP-S8(5) / 152FZ-A19",
            "HTTPS-only (transfer encryption)",
            CheckResult.PASS,
            "HTTPS-only policy is enforced. HTTP access is blocked. Satisfies DPDPA "
            "S.8(5) transport security and 152-FZ Art.19 data transfer protection.",
        ))
    else:
        results.append(CheckResult(
            "DPDP-S8(5) / 152FZ-A19",
            "HTTPS-only (transfer encryption)",
            CheckResult.FAIL,
            "HTTPS-only is NOT enforced. HTTP (unencrypted) access to personal data "
            "is possible. This violates DPDPA S.8(5) and 152-FZ Art.19 simultaneously.",
            "Add a bucket policy denying s3:* where aws:SecureTransport is false. "
            "For 152-FZ PDIS: this endpoint must also support GOST-TLS cipher suites.",
        ))

    return results


# ═══════════════════════════════════════════════════════════════════════════
# CONFLICT ANALYSIS
# ═══════════════════════════════════════════════════════════════════════════

def analyse_conflicts(config, check_results):
    """
    Evaluate which of the 6 identified conflicts are ACTIVE based on
    the check results for this specific configuration.
    """
    conflicts = []
    region    = config.get("region", "unknown").lower()
    enc_algo  = (config.get("encryption_algorithm") or "").upper()
    origin    = config.get("data_subject_origin", "both")
    is_pdis   = config.get("is_pdis", True)

    # Build a quick lookup of check statuses
    status_by_clause = {}
    for r in check_results:
        status_by_clause[r.clause_id] = r.status

    # ── CONFLICT-01: Consent architecture ────────────────────────────────
    # Storage-level: not directly detectable from bucket config alone.
    # But we can flag it as relevant if the system serves both jurisdictions.
    if origin == "both":
        conflicts.append(ConflictResult(
            "CONFLICT-01",
            "DPDP S.6(1) vs 152-FZ Art.9(4)",
            ConflictResult.ACTIVE,
            "This storage serves both Indian and Russian data subjects. Consent "
            "collection architecture requires dual-tier implementation: DPDPA accepts "
            "UI-based affirmative action; 152-FZ Art.9(4) requires a written document "
            "with 9 mandatory elements including passport number and qualified e-signature.",
            "Implement jurisdiction-aware consent engine. Route Russian users to "
            "9-element written consent form; Indian users to UI-based granular consent. "
            "Shared immutable consent audit log with jurisdiction flags.",
        ))
    else:
        conflicts.append(ConflictResult(
            "CONFLICT-01",
            "DPDP S.6(1) vs 152-FZ Art.9(4)",
            ConflictResult.INACTIVE,
            f"Single-jurisdiction data origin ('{origin}'). Consent architecture "
            f"conflict not triggered for this configuration.",
            None,
        ))

    # ── CONFLICT-02: Data localization ────────────────────────────────────
    is_russian_region = (
        region in RUSSIAN_REGIONS or
        any(region.startswith(p) for p in ["ru-", "russia"])
    )
    is_dpdpa_blocked = region in DPDPA_BLACKLISTED_REGIONS

    if origin in ("russian", "both") and not is_russian_region:
        conflicts.append(ConflictResult(
            "CONFLICT-02",
            "242FZ-A18(5) vs DPDP-S16",
            ConflictResult.ACTIVE,
            f"Region '{region}' satisfies DPDPA S.16 (not blacklisted) but violates "
            f"242-FZ Art.18(5) (not a Russian territory). Russian citizen data must be "
            f"initially stored in Russia. DPDPA requires no localization — the two laws "
            f"impose opposite architectural defaults.",
            "Deploy a separate Russian-territory primary bucket (Yandex Cloud "
            "ru-central1 or SberCloud). Implement jurisdictional data routing at "
            "application layer: Russian citizen writes → Russian primary; all others → "
            "current bucket. The bifurcation is architecturally mandatory.",
        ))
    elif is_dpdpa_blocked and is_russian_region:
        conflicts.append(ConflictResult(
            "CONFLICT-02",
            "242FZ-A18(5) vs DPDP-S16",
            ConflictResult.ACTIVE,
            f"Region '{region}' satisfies 242-FZ (Russian territory) but is in a "
            f"country currently blacklisted under DPDPA S.16. Cannot simultaneously "
            f"satisfy both laws with a single storage location.",
            "Contact legal counsel. This configuration represents a currently "
            "irreconcilable conflict requiring regulatory guidance.",
        ))
    else:
        conflicts.append(ConflictResult(
            "CONFLICT-02",
            "242FZ-A18(5) vs DPDP-S16",
            ConflictResult.INACTIVE,
            f"Region '{region}' satisfies both laws currently: "
            f"{'Russian territory (242-FZ ok)' if is_russian_region else 'Not blacklisted (DPDPA ok)'}. "
            f"Monitor DPDPA S.16 blacklist notifications.",
            None,
        ))

    # ── CONFLICT-03: Cryptographic standards ──────────────────────────────
    is_gost = any(g.upper() in enc_algo for g in FZ_ACCEPTABLE_ALGORITHMS)
    is_aes  = ("AES" in enc_algo or "KMS" in enc_algo) and not is_gost
    enc_on  = config.get("encryption_enabled", False)

    if is_pdis and origin in ("russian", "both") and enc_on and is_aes:
        conflicts.append(ConflictResult(
            "CONFLICT-03",
            "152FZ-A19(3b) vs DPDP-S8(5)",
            ConflictResult.ACTIVE,
            f"Encryption algorithm '{config.get('encryption_algorithm')}' satisfies "
            f"DPDPA S.8(5) reasonable safeguards standard (AES accepted) but does NOT "
            f"satisfy 152-FZ Art.19(3b) for regulated PDIS (FSB-certified GOST tools "
            f"mandatory). GOST and AES are incompatible cipher suites.",
            "Implement hybrid encryption by data type: FSB-certified GOST tools "
            "(CryptoPro CSP or ViPNet) for Russian PDIS data; AES-256 for all other "
            "data. Implement crypto abstraction layer — algorithm selection as "
            "deployment-time config. Separate HSMs and PKIs required per jurisdiction.",
        ))
    elif not enc_on:
        conflicts.append(ConflictResult(
            "CONFLICT-03",
            "152FZ-A19(3b) vs DPDP-S8(5)",
            ConflictResult.ACTIVE,
            "No encryption is enabled. Both laws require encryption; 152-FZ additionally "
            "mandates FSB-certified GOST tools. Both violations are simultaneously active.",
            "Enable encryption immediately. Use GOST for Russian PDIS data, AES-256 "
            "elsewhere. See CONFLICT-03 resolution in research paper Section 4.",
        ))
    else:
        note = "GOST detected — satisfies 152-FZ" if is_gost else "Single-jurisdiction or non-PDIS — GOST not required"
        conflicts.append(ConflictResult(
            "CONFLICT-03",
            "152FZ-A19(3b) vs DPDP-S8(5)",
            ConflictResult.INACTIVE,
            f"Cryptographic conflict not triggered for this configuration. {note}.",
            None,
        ))

    # ── CONFLICT-04: Security control prescription ────────────────────────
    # Detectable symptom: no logging + no versioning = likely no 152-FZ UZ compliance
    logging_ok    = config.get("logging_enabled", False)
    versioning_ok = config.get("versioning_enabled", False)
    if is_pdis and origin in ("russian", "both") and (not logging_ok or not versioning_ok):
        missing = []
        if not logging_ok:    missing.append("access logging")
        if not versioning_ok: missing.append("versioning")
        conflicts.append(ConflictResult(
            "CONFLICT-04",
            "DPDP-S8(4) vs 152FZ-A19(1)/A19(3)",
            ConflictResult.ACTIVE,
            f"Missing controls: {', '.join(missing)}. DPDPA S.8(4) requires "
            f"'appropriate' self-assessed measures — gaps may be acceptable under "
            f"DPDPA if risk-assessed. 152-FZ Art.19 prescribes specific mandatory "
            f"controls per UZ classification level — these gaps constitute verifiable "
            f"FSTEC audit failures regardless of risk assessment.",
            "Implement layered compliance architecture: use 152-FZ UZ classification "
            "as the control floor. Enable all required controls per FSTEC Order No.21 "
            "for the applicable UZ level. DPDPA compliance follows automatically.",
        ))
    else:
        conflicts.append(ConflictResult(
            "CONFLICT-04",
            "DPDP-S8(4) vs 152FZ-A19(1)/A19(3)",
            ConflictResult.INACTIVE,
            "No observable security control prescription gaps detected in this "
            "configuration. Note: full CONFLICT-04 assessment requires FSTEC audit "
            "of all PDIS controls, not just storage configuration.",
            None,
        ))

    # ── CONFLICT-05: Transfer adequacy ────────────────────────────────────
    # If bucket is not in Russia but serves Russian users, transfers are occurring
    # that require 152-FZ Art.12(4) legal basis
    if origin in ("russian", "both") and not is_russian_region:
        conflicts.append(ConflictResult(
            "CONFLICT-05",
            "DPDP-S16 vs 152FZ-A12(1)",
            ConflictResult.ACTIVE,
            f"Data of Russian subjects stored in '{region}' (non-Russian territory). "
            f"DPDPA S.16 permits this transfer (no blacklist notification). 152-FZ "
            f"Art.12(1) requires a specific legal basis (Art.12(4)) since India is not "
            f"on Roskomnadzor's adequate countries list. Pre-transfer adequacy "
            f"verification must be documented per Art.12(3).",
            "Document the Art.12(4) legal basis for this transfer (written subject "
            "consent for transborder transfer, or contract performance basis). Build "
            "pre-transfer adequacy verification log. Monitor Roskomnadzor adequacy list "
            "for changes. Note: 242-FZ localization requirement takes precedence.",
        ))
    else:
        conflicts.append(ConflictResult(
            "CONFLICT-05",
            "DPDP-S16 vs 152FZ-A12(1)",
            ConflictResult.INACTIVE,
            f"Transfer adequacy conflict not triggered. "
            f"{'Data is in Russian territory — primary storage obligation satisfied.' if is_russian_region else 'No Russian data subjects in scope.'}",
            None,
        ))

    # ── CONFLICT-06: Automated Decision-Making ────────────────────────────
    # Not directly assessable from bucket config; flag as context-dependent
    if origin in ("russian", "both"):
        conflicts.append(ConflictResult(
            "CONFLICT-06",
            "DPDPA (absent) vs 152FZ-A16",
            ConflictResult.ACTIVE,
            "This storage serves Russian data subjects. If data in this bucket feeds "
            "any automated decision system producing legal consequences (credit scoring, "
            "fraud detection, eligibility assessment), 152-FZ Art.16 requires written "
            "consent for automated processing, an explanation engine, and a 30-day human "
            "objection review workflow. DPDPA has no equivalent provision.",
            "Audit all downstream systems consuming data from this bucket. For any "
            "system producing automated decisions with legal consequences for Russian "
            "subjects: (1) obtain written ADM consent, (2) implement explanation engine, "
            "(3) build 30-day objection handler. Apply 152-FZ standard globally for "
            "architectural simplicity and DPDPA future-proofing.",
        ))
    else:
        conflicts.append(ConflictResult(
            "CONFLICT-06",
            "DPDPA (absent) vs 152FZ-A16",
            ConflictResult.INACTIVE,
            "No Russian data subjects in scope — 152-FZ Art.16 ADM prohibition "
            "not applicable to this configuration.",
            None,
        ))

    return conflicts


# ═══════════════════════════════════════════════════════════════════════════
# REPORT RENDERER
# ═══════════════════════════════════════════════════════════════════════════

# ANSI colour codes (disabled automatically if output is not a terminal)
USE_COLOUR = sys.stdout.isatty()

def clr(text, code):
    return f"\033[{code}m{text}\033[0m" if USE_COLOUR else text

def green(t):  return clr(t, "32")
def red(t):    return clr(t, "31")
def yellow(t): return clr(t, "33")
def cyan(t):   return clr(t, "36")
def bold(t):   return clr(t, "1")
def dim(t):    return clr(t, "2")


def status_fmt(status):
    if status == CheckResult.PASS:  return green(f"{'PASS':6}")
    if status == CheckResult.FAIL:  return red(f"{'FAIL':6}")
    if status == CheckResult.WARN:  return yellow(f"{'WARN':6}")
    if status == CheckResult.SKIP:  return dim(f"{'SKIP':6}")
    return status


def conflict_status_fmt(status):
    if status == ConflictResult.ACTIVE:   return red(f"{'ACTIVE':8}")
    if status == ConflictResult.INACTIVE: return green(f"{'INACTIVE':8}")
    return status


def render_report(config, check_results, conflict_results):
    """Print the full compliance scan report to stdout."""
    W = 72
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    print()
    print(bold("=" * W))
    print(bold(f"  DUAL-JURISDICTION COMPLIANCE SCAN REPORT"))
    print(bold(f"  DPDPA 2023  |  Federal Law 152-FZ / 242-FZ"))
    print(bold("=" * W))
    print(f"  Target  : {bold(config['bucket_name'])}")
    print(f"  Region  : {config['region']}")
    print(f"  Origin  : {config.get('data_subject_origin','both')} data subjects")
    print(f"  PDIS    : {'Yes' if config.get('is_pdis') else 'No'}")
    print(f"  Scanned : {ts}")
    print(f"  Version : {VERSION}")
    print()

    # ── Clause-level results ──────────────────────────────────────────────
    print(bold("  CLAUSE-LEVEL RESULTS"))
    print("  " + "-" * (W - 2))
    print(f"  {'Clause ID':<28} {'Check':<36} {'Status'}")
    print("  " + "-" * (W - 2))

    for r in check_results:
        cid   = cyan(f"{r.clause_id:<28}")
        cname = f"{r.check_name:<36}"
        print(f"  {cid} {cname} {status_fmt(r.status)}")
        print(f"  {' '*28}   {dim(r.detail)}")
        if r.recommendation and r.status in (CheckResult.FAIL, CheckResult.WARN):
            # Wrap recommendation text
            words = r.recommendation.split()
            lines = []
            line  = ""
            for w in words:
                if len(line) + len(w) + 1 > 55:
                    lines.append(line)
                    line = w
                else:
                    line = (line + " " + w).strip()
            if line:
                lines.append(line)
            prefix = f"  {' '*28}   {yellow('→ ')}"
            for i, ln in enumerate(lines):
                pad = f"  {' '*28}     " if i > 0 else prefix
                print(f"{pad}{yellow(ln)}")
        print()

    # ── Conflict analysis ─────────────────────────────────────────────────
    print(bold("  CONFLICT ANALYSIS"))
    print("  " + "-" * (W - 2))

    active_count = sum(1 for c in conflict_results if c.status == ConflictResult.ACTIVE)
    if active_count == 0:
        print(f"  {green('No conflicts triggered for this configuration.')}")
    else:
        for c in conflict_results:
            print(f"  {cyan(c.conflict_id):<20} {dim(c.laws):<40} "
                  f"{conflict_status_fmt(c.status)}")
            if c.status == ConflictResult.ACTIVE:
                # Wrap detail
                words = c.detail.split()
                lines = []
                line  = ""
                for w in words:
                    if len(line) + len(w) + 1 > 62:
                        lines.append(line)
                        line = w
                    else:
                        line = (line + " " + w).strip()
                if line: lines.append(line)
                for ln in lines:
                    print(f"  {'':20}   {dim(ln)}")
                if c.recommendation:
                    words = c.recommendation.split()
                    lines = []
                    line  = ""
                    for w in words:
                        if len(line) + len(w) + 1 > 60:
                            lines.append(line)
                            line = w
                        else:
                            line = (line + " " + w).strip()
                    if line: lines.append(line)
                    for i, ln in enumerate(lines):
                        pad = f"  {'':20}   {yellow('→ ')}" if i == 0 else f"  {'':20}     "
                        print(f"{pad}{yellow(ln)}")
            print()

    # ── Summary ───────────────────────────────────────────────────────────
    total    = len(check_results)
    passed   = sum(1 for r in check_results if r.status == CheckResult.PASS)
    failed   = sum(1 for r in check_results if r.status == CheckResult.FAIL)
    warned   = sum(1 for r in check_results if r.status == CheckResult.WARN)
    skipped  = sum(1 for r in check_results if r.status == CheckResult.SKIP)
    active_c = sum(1 for c in conflict_results if c.status == ConflictResult.ACTIVE)
    total_c  = len(conflict_results)

    print(bold("  SUMMARY"))
    print("  " + "-" * (W - 2))
    print(f"  Checks passed   : {green(str(passed))} / {total}")
    print(f"  Checks failed   : {red(str(failed))} / {total}")
    print(f"  Warnings        : {yellow(str(warned))} / {total}")
    print(f"  Skipped         : {dim(str(skipped))} / {total}  (out-of-scope checks)")
    print(f"  Conflicts active: {red(str(active_c)) if active_c > 0 else green('0')} / {total_c}")

    # Overall posture
    print()
    if failed == 0 and active_c == 0:
        print(f"  {green(bold('OVERALL POSTURE: COMPLIANT'))}  — No failures or active conflicts.")
    elif failed <= 2 and active_c <= 2:
        print(f"  {yellow(bold('OVERALL POSTURE: PARTIAL'))}   — Remediation required for items above.")
    else:
        print(f"  {red(bold('OVERALL POSTURE: NON-COMPLIANT'))}  — Critical failures detected.")

    print(bold("=" * W))
    print()

    return {
        "passed": passed, "failed": failed, "warned": warned,
        "skipped": skipped, "active_conflicts": active_c,
    }


# ═══════════════════════════════════════════════════════════════════════════
# JSON EXPORT
# ═══════════════════════════════════════════════════════════════════════════

def export_json(config, check_results, conflict_results, summary, output_path):
    data = {
        "scanner_version": VERSION,
        "scan_timestamp":  datetime.now(timezone.utc).isoformat(),
        "target":          config,
        "check_results":   [r.to_dict() for r in check_results],
        "conflict_results":[c.to_dict() for c in conflict_results],
        "summary":         summary,
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  JSON report saved → {output_path}\n")

USE_COLOUR = False

config = dict(SIMULATED_CONFIGS["mixed"])
checks    = run_checks(config)
conflicts = analyse_conflicts(config, checks)
summary   = render_report(config, checks, conflicts)

config = dict(SIMULATED_CONFIGS["pass"])
checks    = run_checks(config)
conflicts = analyse_conflicts(config, checks)
summary   = render_report(config, checks, conflicts)

config = dict(SIMULATED_CONFIGS["fail"])
checks    = run_checks(config)
conflicts = analyse_conflicts(config, checks)
summary   = render_report(config, checks, conflicts)